MONGO_URI: "mongodb://localhost:27017"
MONGO_DBNAME: "mielenosoitukset"
STATE_SOURCE_MONGO_URI: "mongodb://localhost:27017"
STATE_SOURCE_DBNAME: "mielenosoitukset"

MOSOFI:
  BASE_URL: https://mielenosoitukset.fi/ 
  ACCESS_TOKEN:
  POST_MAX_DAYS: # max days till a demo we are posting
      60
  CHECK_INTERVAL: # seconds between each check of api
    60

MASTODON:
  BASE_URL: 
  ACCESS_TOKEN: 


LOG_LEVEL: WARN
